name: find_my_staff
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.1
  google_sign_in: ^6.1.0
  floating_bottom_navigation_bar: ^1.5.2
  syncfusion_flutter_datepicker: "20.4.44"
  location: ^4.4.0
  flutter_rating_bar: ^4.0.1
  provider: ^5.0.0
  intl: ^0.18.0
  images_picker: ^1.2.11
  image_picker: ^1.0.1
  firebase_storage: ^11.2.6
  get: ^4.3.8
  get_storage: ^2.0.3
  flutter_localizations:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
